# hit_data.gd
# A plain data class passed through the hit_received signal.
# Carries everything the target needs to respond: damage, knockback vector,
# hitstun duration, and the attacker identity.
#
# Generated by CombatController during ACTIVE frames when a hurtbox is found.
# Consumed by the target's health/physics system.
#
class_name HitData

var attacker: Node2D           # the player node who dealt the hit
var attack_id: String          # e.g. "light", "heavy" — for VFX/sound routing
var damage: float
var knockback_vector: Vector2  # pre-computed world-space knockback impulse
var hitstun_frames: int

# CombatController builds this when a hit is confirmed:
#
#   var hit = HitData.new()
#   hit.attacker        = owner           # player node
#   hit.attack_id       = attack_data.attack_id
#   hit.damage          = attack_data.damage
#   hit.knockback_vector = _compute_knockback(target_pos, attack_data)
#   hit.hitstun_frames  = attack_data.hitstun_frames
#   target_hurtbox.hit_received.emit(hit)
