# hit_data.gd
# Plain data struct passed through the hit_received signal.
# Generated by CombatController, consumed by the target's health/physics system.
#
# IMPORTANT FIELDS FOR RPS RESOLUTION:
#   attack_type  — "light" or "heavy". Used by the receiver to check guard/armor.
#   is_reflected — true when this hit originated as a parry reflection.
#                  The receiver should NOT trigger another parry on a reflected hit
#                  (no infinite reflection loops).
#   was_parried  — set to true by Parry.on_hit_incoming() when the hit is intercepted.
#                  Read by CombatController._query_hits() AFTER emitting hit_received
#                  to suppress combo credit and the HIT log for the attacker.
#
class_name HitData

var attacker: Node2D            # player node who dealt the hit (or was reflected from)
var attack_id: String           # e.g. "sword_light", "sword_heavy" — VFX/sound routing
var attack_type: String         # "light" or "heavy" — used for RPS resolution
var damage: float
var knockback_vector: Vector2   # pre-computed world-space knockback impulse
var hitstun_frames: int
var is_reflected: bool = false  # true if this is a parry reflection — skip parry check
var was_parried: bool  = false  # set true by Parry when successfully intercepted
